Adding Rubocop ruby linter
feministy/cryptozoologist pull request #28
Opened 2017-09-20 02:10 UTC by Br3nda

i saw you have code climate enabled, but have a really low score at the moment

this adds rubocop, which can then be used to lint the code and then we can gradually make the small improvements to make the code climate score better (more readable code, less repetition etc)

2017-09-21 01:08 UTC, slothelle requested changes
This is awesome! I think probably a big part of the poor score are some of the architectural decisions I made early on for instructional purposes in this gem - but now that it no longer serves this purpose I would _love_ to get a refactor in!

_a n y w a y s_

Would you mind adding some documentation to the `README` about how to use rubocop? It would be much appreciated 😊 

Thanks for this and the other PRs! They're super helpful!

2017-09-22 07:15 UTC, Br3nda commented
Happy to. Will look for time this weekend.

2018-09-05 01:51 UTC, Br3nda commented
@feministy it's all updated.
If you're happy to merge, i'll follow up with a couple pull requests that make the code follow the new settings.

2018-11-08 10:48 UTC, Br3nda commented
@feministy anything else needed here?

2018-11-25 06:25 UTC, Br3nda commented
Closing to get this off my github lisy. Feel free to open if you want this contribution.

2018-11-25 06:25 UTC, closed without merging